Dockerイメージ公開用ファイルを追加
approvers/vcListBot pull request #4
Opened 2020-07-06 08:48 UTC by kawaemon

containersに移行するために。

2020-07-06 12:44 UTC, siketyan requested changes

2020-07-06 12:44 UTC, Siketyan commented on .github/workflows/docker.yaml
> +      - master
タグ (ry

2020-07-08 01:04 UTC, kawaemon commented on .github/workflows/docker.yaml
> +      - master
078b0ea 
気づいてませんでした。。。遅れてごめんなさい。。。

2020-07-08 01:04 UTC, siketyan approved these changes

2020-07-08 01:08 UTC, merged